export const messages = {
  registration: {
    nickname: {
      prompt: '😊 请问我们该怎样称呼你呢？',
      validation: '❌ 昵称不能为空，请重新输入'
    },
    phone: {
      prompt: '📱 请提供你的联系方式\n例如：0123456789 或 +60123456789',
      validation: '❌ 手机号格式错误，请重新输入\n例如：0123456789 或 +60123456789'
    },
    income: {
      prompt: '💰 请告诉我们你的月收入（RM）\n例如：5000',
      validation: '❌ 请输入有效金额（大于0，最多两位小数）\n例如：5000'
    },
    budgetA: {
      prompt: '🛒 请设置【生活开销】预算占比\n*包含日常消费、餐饮、交通等\n例如：60 或 60%\n💡 设置后可随时调整',
      validation: '❌ 请输入0-100之间的百分比\n例如：60 或 60%'
    },
    budgetB: {
      prompt: '📚 请设置【学习投资】预算占比\n例如：30 或 30%',
      validation: '❌ 请输入0-100之间的百分比'
    },
    budgetOverflow: '❌ 生活开销 + 学习投资 超过100%\n当前总计：{total}%\n请重新设置学习投资占比',
    travelBudget: {
      prompt: '✈️ 设置你的年度旅游目标（RM）\n将按年额÷12计入【学习投资】月度进度（不直接入账）\n例如：12000',
      validation: '❌ 请输入有效金额\n例如：3600'
    },
    lastMonthSpendingPct: {
      prompt: '📊 请输入上月实际开销占收入的百分比\n*用于本月预算参考对比\n例如：如上月花费3000，收入5000，则输入60%',
      validation: '❌ 请输入有效百分比（0-100）\n例如：60 或 60%'
    },
    branch: {
      prompt: '🏢 请选择你所属的分行：'
    },
    sessionExpired: '⏰ 会话已过期，请重新执行 /start',
    success: '🎉 欢迎加入 LEARNER CLUB！\n\n💡 你的预算配置：\n• 生活开销：{budgetA}%\n• 学习投资：{budgetB}%\n• 储蓄投资：{budgetC}%\n🏢 所属分行：{branch}\n\n✨ 开始你的财务管理之旅：\n• /record - 记录支出\n• /my month - 查看进度'
  },
  settings: {
    choose: '🛠️ 请选择要修改的项目：',
    updated: '✅ 已更新。',
    summary: '📄 当前资料\n昵称：{nickname}\n电话：{phone}\n收入：RM {income}\n生活开销占比：{a_pct}%\n学习投资占比：{b_pct}%\n旅游年额：RM {travel}\n年度医疗保险：RM {ins_med}\n年度车险：RM {ins_car}\n分行：{branch}',
    fields: {
      nickname: '昵称',
      phone: '联系方式',
      income: '月收入',
      a_pct: '生活开销占比',
      b_pct: '学习投资占比',
      travel: '年度旅游目标',
      branch: '所属分行'
    }
  },
  record: {
    choose_group: '💡 请选择支出类别：',
    choose_category: '✅ 已选择：{group}\n请选择具体分类：',
    amount_prompt: '💰 请输入金额：\n*支持整数或小数，如：12.50',
    amount_invalid: '❌ 金额格式错误\n请输入0-1,000,000之间的数值',
    note_prompt: '📝 添加备注（可选）：\n*发送 /skip 跳过此步骤',
    preview: '📋 确认信息：\n类别：{groupLabel}\n分类：{category}\n金额：RM {amount}\n备注：{note}\n\n确认无误请点击 ✅',
    save_failed: '❌ 保存失败，请重试',
    canceled: '❌ 操作已取消',
    saved: '✅ 记录成功！\n{groupLabel}：RM {amount}'
  },
  my: {
    need_start: '⚠️ 请先完成设置：/start',
    summary: '📊 {range} 数据总览\n\n💰 实际支出与占比：\n• 开销：RM {a}（{ra}）\n• 学习：RM {b}（{rb}）\n• 储蓄：RM {c}（{rc}）*\n\n🎯 目标占比：\n• 开销 {a_pct}%\n偏差：开销 {da}%\n💡 开销额度：{a_gap_line}\n\n🗓 当前资料：\n• 收入：RM {income}\n• 目标：开销 RM {cap_a}\n• EPF（含入储蓄）：RM {epf}\n• 旅游基金（月）：RM {travel}\n• 医疗保险（月）：RM {medical}\n• 车险（月）：RM {car_insurance}\n*储蓄含EPF\n\n📋 分类明细：\n{category_details}'
  },
  admin: {
    no_perm: '⚠️ 权限不足',
    usage: '❌ 用法：/broadcast 消息内容',
    sent: '✅ 广播完成，已发送 {n} 条消息'
  },
  help: '❓ LEARNER CLUB 功能指南：\n• /start - 初始设置\n• /record - 记录支出\n• /my - 查看统计（支持 today/month/lastmonth）',
  post: {
    again: '再记一笔',
    my: '查看统计'
  },
  history: {
    listHeader: '🧾 近期记录（{range}）',
    noRecords: '（无记录）',
    hint: '提示：点击每行后的按钮进行编辑或删除',
    autoGeneratedNote: '🔒 系统自动生成的记录不可编辑，请在设置中调整相关配置',
    viewRecord: '📋 查看记录详情',
    editChoose: '请选择要修改的内容：',
    editAmount: '改金额',
    editNote: '改备注',
    backList: '返回列表',
    amountPrompt: '请输入新的金额（RM）',
    notePrompt: '请输入新的备注（最多200字）',
    updated: '✅ 已更新',
    deleteConfirm: '确认删除这条记录？',
    deleted: '✅ 已删除'
  },
  start_saved: '✅ 资料保存成功！\n\n快速开始：\n• /record - 记录一笔支出\n• /my - 查看本月进度'
}

// 添加 zh 对象，包含 cron 相关的消息模板
export const zh = {
  cron: {
    reminder: '🔔 今日提醒\n\n📅 今天是 {date}\n💡 记得记录今天的支出哦！\n\n💰 今日进度：\n• 开销：RM {a}\n• 学习：RM {b}\n• 储蓄：RM {c}\n\n📊 本月占比：\n• 开销：{ra}%\n• 学习：{rb}%\n• 储蓄：{rc}%\n\n🎯 保持记录，管理财务！',
    morning_rank: '🌅 早安！\n\n🏆 今日排名：第 {rank} 名\n\n📊 排行榜 TOP 15：\n{top}\n\n💪 继续加油，保持记录！',
    branch_lead: '🏢 分行排行榜\n\n🏆 {code} 分行\n• 完成率：{rate}%\n• 完成人数：{done}/{total}\n• 近7天平均：{avg7}%\n\n🎯 目标：100% 完成率！',
    daily_report: '📊 今日日报\n\n💰 今日支出：\n• 开销：RM {a}\n• 学习：RM {b}\n• 储蓄：RM {c}\n\n📈 本月占比：\n• 开销：{ra}%\n• 学习：{rb}%\n• 储蓄：{rc}%\n\n✈️ 旅游基金（月）：RM {travel}\n\n💡 保持记录，管理财务！'
  }
}

